# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "remarque@writers.net",
  "avatarPath": "remarque.png",
  "firstname": "Erich",
  "lastname": "Remarque",
  "password": "front1919",
  "type": "regular"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "remarque@writers.net",
  "password": "front1919"
}

###

## Отправить изображение

POST http://localhost:4000/users/654fc55d04a7665292c7f920/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="pass.jpg"
Content-Type: image/jpeg

< /Users/drnickopol/Desktop/pass.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJlbWFycXVlQHdyaXRlcnMubmV0IiwiZmlyc3RuYW1lIjoiRXJpY2giLCJsYXN0bmFtZSI6IlJlbWFycXVlIiwiaWQiOiI2NTRmYzU1ZDA0YTc2NjUyOTJjN2Y5MjAiLCJ0eXBlIjoicmVndWxhciIsImlhdCI6MTY5OTc5MTQ2NCwiZXhwIjoxNjk5OTY0MjY0fQ.QfEs2rPlKnrahOB5Ghru_EVY7z_Yd0V36oJtvSV7W3Y

###
